apiVersion: v1
kind: LimitRange
metadata:
  name: "{{ocp_unconstrained_project}}-core-resource-limits"
  namespace: "{{ocp_unconstrained_project}}"
spec:
  limits:
  - default:
      cpu: 1
      memory: "{{container_default_mem}}"
    defaultRequest:
      cpu: 50m
      memory: 256Mi
    max:
      memory: "{{container_max_mem}}"
    min:
      memory: 10Mi
    type: Container
  - max:
      memory: "{{pod_max_mem}}"
    min:
      memory: "{{pod_min_mem}}"
    type: Pod
