insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('329299', 'Redhat','Red Fedora Official Red Hat Fedora', 34.99)
insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('329199', 'catalog','Forge Laptop Sticker JBoss Community Forge Project Sticker', 8.50)
insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('165613', 'catalog','Forge Laptop Sticker JBoss Community Forge Project Sticker', 10.50)
insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('165954', 'openshift', 'Raleigh', 90)
insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('444434', 'catalog', 'Red Fedora Official Red Hat Fedora', 34.99)
insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('444435', 'catalog','Tokyo Official Red Hat Fedora', 20.0)
insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('444436', 'catalog','India Official Red Hat Fedora', 100)
