insert into PRODUCT_INVENTORY (itemId, link, location, quantity) values ('329299', 'http://maps.google.com/?q=Raleigh', 'Raleigh', 35)
insert into PRODUCT_INVENTORY (itemId, link, location, quantity) values ('329199', 'http://maps.google.com/?q=Raleigh', 'Raleigh', 12)
insert into PRODUCT_INVENTORY (itemId, link, location, quantity) values ('165613', 'http://maps.google.com/?q=Raleigh', 'Raleigh', 45)
insert into PRODUCT_INVENTORY (itemId, link, location, quantity) values ('165954', 'http://maps.google.com/?q=Raleigh', 'Raleigh', 87)
insert into PRODUCT_INVENTORY (itemId, link, location, quantity) values ('444434', 'http://maps.google.com/?q=Raleigh', 'Raleigh', 43)
insert into PRODUCT_INVENTORY (itemId, link, location, quantity) values ('444435', 'http://maps.google.com/?q=Raleigh', 'Raleigh', 32)
insert into PRODUCT_INVENTORY (itemId, link, location, quantity) values ('444436', 'http://maps.google.com/?q=Tokyo', 'Tokyo', 53)

insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('329299', 'Redhat','Red Fedora Official Red Hat Fedora', 34.99)
insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('329199', 'catalog','Forge Laptop Sticker JBoss Community Forge Project Sticker', 8.50)
insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('165613', 'catalog','Solid Performance Polo Moir.', 17.80)
insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('444456', 'catalog', 'Red Fedora Official Red Hat Fedora', 34.99)
insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('444435', 'catalog','Tokyo Official Red Hat Fedora', 34.99)
insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('444436', 'catalog','India Official Red Hat Fedora', 34.99)