insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('329299', 'Redhat','Red Fedora Official Red Hat Fedora', 34.99)
insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('329199', 'catalog','Forge Laptop Sticker JBoss Community Forge Project Sticker', 8.50)
insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('165613', 'catalog','Solid Performance Polo Moir.', 17.80)
insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('444456', 'catalog', 'Red Fedora Official Red Hat Fedora', 34.99)
insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('444435', 'catalog','Tokyo Official Red Hat Fedora', 34.99)
insert into PRODUCT_CATALOG (itemId, name, description, price ) values ('444436', 'catalog','India Official Red Hat Fedora', 34.99)